services:
  server:
    build: ./Server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./Server:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=feelhippo
      - POSTGRES_PASSWORD=Filippo333
      - POSTGRES_DB=auth
      - SQL_HOST=db
      - SQL_PORT=5432
  client:
    build: ./Client
    command: python manage.py runserver 0.0.0.0:3000
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/usr/src/app
    links:
      - server:my-oauth2-server.dev

volumes:
  postgres_data: